- Cesium.Compiler/Arguments.cs
- Cesium.Compiler/Program.cs
- Cesium.Compiler/RuntimeConfig.cs
- Cesium.sln.DotSettings
- README.md
> Support for runtimeconfig.json generation

- Cesium.CodeGen.Tests/CodeGenTestBase.cs
- Cesium.CodeGen.Tests/CodeGenTests.DefaultedFrameworkTest.verified.txt
- Cesium.CodeGen.Tests/CodeGenTests.FrameworkTest_targetFramework=SystemRuntime_versionString=4.2.2.0.verified.txt
- Cesium.CodeGen.Tests/CodeGenTests.FrameworkTest_targetFramework=mscorlib_versionString=4.0.0.0.verified.txt
- Cesium.CodeGen.Tests/CodeGenTests.FrameworkTest_targetFramework=netstandard_versionString=2.1.0.0.verified.txt
- Cesium.CodeGen.Tests/CodeGenTests.cs
- Cesium.CodeGen.Tests/TargetRuntimeTest.DefaultedFrameworkTest.verified.txt
- Cesium.CodeGen.Tests/TargetRuntimeTest.FrameworkTest_targetFramework=MsCorLib_systemAssemblyVersionString=4.0.0.0_frameworkVersionString=4.8.verified.txt
- Cesium.CodeGen.Tests/TargetRuntimeTest.FrameworkTest_targetFramework=NetStandard_systemAssemblyVersionString=2.1.0.0_frameworkVersionString=2.1.verified.txt
- Cesium.CodeGen.Tests/TargetRuntimeTest.FrameworkTest_targetFramework=SystemRuntime_systemAssemblyVersionString=4.2.2.0_frameworkVersionString=6.0.verified.txt
- Cesium.CodeGen.Tests/TargetRuntimeTests.cs
- Cesium.CodeGen/Generator.cs
- Cesium.CodeGen/TargetRuntime.cs
- Cesium.Compiler/Arguments.cs
- Cesium.Compiler/Program.cs
> (#10) Generator: emit TargetFrameworkAttribute

- Cesium.Parser.Tests/LexerTests.cs
My apologies for creative tests which make your code suffer.
> Add test for C identifier rules

- Cesium.Parser.Tests/LexerTests.cs
> Explicitly ask in tests for Unicode characters support

- Cesium.Compiler/Arguments.cs
- Cesium.Compiler/Program.cs
I do have plans to use that in the E2E tests, to reduce verboseness of comparison
> Add ability to suppress compiler logo

- .vscode/launch.json
- .vscode/tasks.json
I'm not of a fan of using VS Code over VS, but on my Gentoo laptop at home this is best option IMO.
> Add basic VSCode configuration

- Cesium.Compiler/Program.cs
This should help troubleshoot errors in #34 like here https://github.com/ForNeVeR/Cesium/runs/4669456009?check_suite_focus=true
> Display parsing errors

- Cesium.Compiler/Cesium.Compiler.csproj
- Cesium.Compiler/Program.cs
- Cesium.Compiler/stdlib/stdio.h
- Cesium.Compiler/stdlib/stdlib.h
- Cesium.IntegrationTests/stdio_test.c
- Cesium.IntegrationTests/stdlib_test.c
- Cesium.Runtime/Cesium.Runtime.csproj
- Cesium.Runtime/StdIoFunctions.cs
- Cesium.Runtime/StdLibFunctions.cs
- Cesium.Runtime/StringFunctions.cs
- Cesium.sln
> Add basic runtime library

- Cesium.Samples/hello.c
This now actually prints "hello, world".
> Samples: improve hello.c

- Cesium.IntegrationTests/Run-Tests.ps1
- README.md
This parameter useful for debugging integration tests
> Add option to run just single test case

- Cesium.CodeGen.Tests/CodeGenMethodTests.AssigmentLoweringTest.verified.txt
- Cesium.CodeGen.Tests/CodeGenMethodTests.CharConstTest.verified.txt
- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/CodeGenTestBase.cs
- Cesium.CodeGen/Generators/Expressions.cs
- Cesium.CodeGen/Generators/Functions.cs
- Cesium.CodeGen/Generators/Lowering.cs
- Cesium.IntegrationTests/Run-Tests.ps1
- Cesium.IntegrationTests/arithmetics.c
- Cesium.IntegrationTests/comments.ignore.c
- Cesium.IntegrationTests/stdlib_test.c
- Cesium.Parser.Tests/ParserTests/DeclarationParserTests.cs
- Cesium.Parser.Tests/ParserTests/FullParserTests.CharLiteral.verified.txt
- Cesium.Parser.Tests/ParserTests/FullParserTests.cs
- Cesium.Parser.Tests/ParserTests/StatementParserTests.cs
- Cesium.Test.Framework/ParserResultExtensions.cs
- Cesium.Test.Framework/ParserTestBase.cs
Not because something important here, but because I wrote it during unrest in Almaty.
Will gather feedback and probably split on couple PR's when have free time.
Better look by individual commits.
I add concept of lowering, because that's important for simplification of codegen. Please think about it.
> Revolutionary PR

- Cesium.IntegrationTests/Cesium.IntegrationTests.proj
- Cesium.sln
Also re-save VS solution to make it happy during Build All
> Teach integration tests to build

- Cesium.sln
- README.md
- docs/type-system.md
> (#57) Docs: document the type system

- Cesium.Parser.Tests/PreprocessorTests/PreprocessorTests.cs
- Cesium.Preprocessor/CPreprocessor.cs
- Cesium.Preprocessor/CPreprocessorExceptions.cs
> Preprocessor: Naive implementation of #error

- Cesium.Preprocessor/CPreprocessor.cs
- Cesium.Preprocessor/CPreprocessorExceptions.cs
- Cesium.Preprocessor/PreprocessorException.cs
- README.md
> (#63) Preprocessor: minor fixes, doc update

- README.md
After the recent addition of subtasks, it is now closer to 10%.
> Docs: update the milestone status

- Cesium.Ast/Statements.cs
- Cesium.CodeGen.Tests/CodeGenIfTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfElseTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfImplicitElseTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenIfTests.SimpleIfTest.verified.txt
- Cesium.CodeGen/Extensions/BlockItemEx.cs
- Cesium.CodeGen/Ir/BlockItems/IfElseStatement.cs
- Cesium.Parser.Tests/ParserTests/StatementParserTests.cs
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.IfElseStatement.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.IfStatement.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.NestedIfs.verified.txt
- Cesium.Parser/CParser.cs
> If else statement

- Cesium.Compiler/Arguments.cs
- Cesium.Compiler/Compilation.cs
- Cesium.Compiler/Main.cs
- README.md
> Module kind arg

- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ArrayAddressOf.verified.txt
- Cesium.CodeGen/Ir/Expressions/LValues/LValueArrayElement.cs
> (#133) Implement address of array elements

- Cesium.CodeGen/Contexts/AssemblyContext.cs
- Cesium.Compiler/Arguments.cs
- Cesium.Compiler/Compilation.cs
- Cesium.Compiler/Main.cs
Added Namespace argument and Namespace property in AssemblyContext
> Namespace argument

- Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
- Cesium.CodeGen/Ir/Expressions/PointerMemberAccessExpression.cs
- Cesium.CodeGen/Ir/TopLevel/TopLevelDeclaration.cs
- Cesium.CodeGen/Ir/Types/FunctionType.cs
- Cesium.CodeGen/Ir/Types/StructType.cs
- Cesium.Compiler/Compilation.cs
- Cesium.Parser/CParser.cs
- Cesium.Parser/ParseException.cs
- Cesium.Parser/TokenExtensions.cs
- Cesium.sln.DotSettings
This fixes all the Sonar issues except the `TODO`s and an actual "bug" (which is caused by Cesium not processing `const` declarations, yet).
> Project: code cleanup

- Cesium.CodeGen.Tests/CodeGenTestBase.cs
- Cesium.CodeGen.Tests/CodeGenTypeTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.GlobalClassFQNTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.GlobalClassTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.NamespaceTest.verified.txt
- Cesium.CodeGen/Contexts/AssemblyContext.cs
- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
- Cesium.CodeGen/Ir/TopLevel/FunctionDefinition.cs
- Cesium.Compiler/Arguments.cs
- Cesium.Compiler/Compilation.cs
- Cesium.Compiler/Main.cs
Closes #35.
Added GlobalFunctions Type
Change function emit from Module Type to GlobalFunctions
> GlobalFunctions Type

- Cesium.CodeGen.Tests/CliImportTests.cs
- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/verified/CliImportTests.CliImportTest.verified.txt
- Cesium.CodeGen/Ir/TopLevel/TopLevelDeclaration.cs
- Cesium.Compiler/stdlib/stdio.h
- Cesium.IntegrationTests/Run-Tests.ps1
- Cesium.Runtime/StdIoFunctions.cs
- README.md
> Method signature validation in __cli_import.

- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.StandardMain.verified.txt
- Cesium.CodeGen/Ir/TopLevel/FunctionDefinition.cs
> Remove try finally

- Cesium.CodeGen.Tests/CodeGenIfTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfElseReturnTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfElseTest.verified.txt
- Cesium.CodeGen/Ir/BlockItems/IfElseStatement.cs
> Optimized if-else when "true" branch always returns.

- Cesium.CodeGen/Ir/Expressions/BinaryOperators/LogicalBinaryOperatorExpression.cs
> (#118) CodeGen: remove the TODO notes since we've decided they aren't important

- Cesium.CodeGen.Tests/verified/CodeGenForTests.ForTest_NoInit.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfElseTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.AddressOfTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.AmbiguousCallTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.Arithmetic.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ArrayAddressOf.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ArrayAssignment.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.AssigmentLoweringTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.BitOrAssignmentLoweringTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.CharConstTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.MultiDeclaration.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.PostfixIncrementTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.SimpleVariableTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.AddIntToChar.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ArrayDeclaration.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ConstCharLiteralDeduplication.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ConstCharLiteralTest.verified.txt
- Cesium.CodeGen/Extensions/CodeGenEx.cs
- Cesium.CodeGen/Ir/Expressions/LValues/LValueLocalVariable.cs
Move optimization from LValueLocalVariable into CodeGenEx
> Local variable set optimization

- .idea/.idea.Cesium/.idea/inspectionProfiles/Project_Default.xml
- Cesium.sln
- README.md
- docs/tests.md
- docs/type-system.md
Added a separate document on writing tests in Cesium, and performed small proofread whenever Grazie Pro told me the phrases were incorrect.
> Docs: testing notes

- Cesium.CodeGen/Contexts/ForScope.cs
- Cesium.CodeGen/Contexts/FunctionScope.cs
- Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
- Cesium.CodeGen/Contexts/IDeclarationScope.cs
- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
- Cesium.CodeGen/Extensions/TypeSystemEx.cs
- Cesium.CodeGen/Ir/Expressions/ConstantExpression.cs
- Cesium.CodeGen/Ir/Expressions/Constants/CharConstant.cs
- Cesium.CodeGen/Ir/Expressions/Constants/IConstant.cs
- Cesium.CodeGen/Ir/Expressions/Constants/IntegerConstant.cs
- Cesium.CodeGen/Ir/Expressions/Constants/StringConstant.cs
- Cesium.CodeGen/Ir/Types/CTypeSystem.cs
This is to allow think how generate code in C terms, and not in CLR term, and have C<->CLR interop logic across codebase.
Convert constants to new concept to show how I see migration process
> Create rudimentary C type system

- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/CodeGenTypeTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.FunctionPtrTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.FunctionPtrWithParamsTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ImplicitReturnAllowedForMain.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.PrimitiveTypes.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.UninitializedVariable.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ArrayDeclaration.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.BasicTypeDef.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.TypeDefStructUsage.verified.txt
- Cesium.CodeGen/Contexts/AssemblyContext.cs
- Cesium.CodeGen/Contexts/ForScope.cs
- Cesium.CodeGen/Contexts/FunctionScope.cs
- Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
- Cesium.CodeGen/Contexts/IDeclarationScope.cs
- Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
- Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs
- Cesium.CodeGen/Ir/TopLevel/TopLevelDeclaration.cs
That way we working more on C-types then Cecil internals
> Declare variables by IType, and not by VariableDef

- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.EqualToOperatorBoolToIntConversion.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.EqualToOperatorFalseBoolToIntConversion.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.EqualToOperatorTrueBoolToIntConversion.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.IntToBoolConversion.verified.txt
- Cesium.CodeGen/Extensions/TypeSystemEx.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/ComparisonBinaryOperatorExpression.cs
- Cesium.IntegrationTests/bool_conversion.c
> Type compatibility check

- Cesium.CodeGen.Tests/CodeGenIfTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfNegationTest.verified.txt
- Cesium.CodeGen/Ir/Expressions/UnaryOperator.cs
- Cesium.CodeGen/Ir/Expressions/UnaryOperatorExpression.cs
- Cesium.Parser.Tests/ParserTests/StatementParserTests.cs
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.NotFuncCall.verified.txt
- Cesium.Parser/CParser.cs
I would like to simplify that by changing model for IfElseStatment to have differnet mode for branching, but that's require changes in lowering, and I feel that's too complicated
Related to #197
> Add support for negation in expressions

- .editorconfig
- Cesium.CodeGen/Ir/Expressions/AssignmentExpression.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/ArithmeticBinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/BitwiseBinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/LogicalBinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/ConstantExpression.cs
- Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
- Cesium.CodeGen/Ir/Expressions/IExpression.cs
- Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs
- Cesium.CodeGen/Ir/Expressions/IndirectionExpression.cs
- Cesium.CodeGen/Ir/Expressions/MemberAccessExpression.cs
- Cesium.CodeGen/Ir/Expressions/PrefixIncrementExpression.cs
- Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
- Cesium.CodeGen/Ir/Expressions/UnaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/Values/IValue.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueArrayElement.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueField.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueLocalVariable.cs
Also normalize line endings in the file
> Remove unused namespaces

- Cesium.CodeGen/Ir/Declarations/LocalDeclarationInfo.cs
- Cesium.CodeGen/Ir/Types/StructType.cs
That allow us to perform analysys of member access before emit phase
> Make struct members public

- Cesium.CodeGen/Contexts/ForScope.cs
- Cesium.CodeGen/Contexts/FunctionScope.cs
- Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
- Cesium.CodeGen/Contexts/IDeclarationScope.cs
- Cesium.CodeGen/Contexts/IEmitScope.cs
- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
- Cesium.CodeGen/Ir/BlockItems/AmbiguousBlockItem.cs
- Cesium.CodeGen/Ir/BlockItems/CompoundStatement.cs
- Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
- Cesium.CodeGen/Ir/Expressions/AssignmentExpression.cs
- Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
- Cesium.CodeGen/Ir/Expressions/GetAddressValueExpression.cs
- Cesium.CodeGen/Ir/Expressions/GetValueExpression.cs
- Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs
- Cesium.CodeGen/Ir/Expressions/IndirectionExpression.cs
- Cesium.CodeGen/Ir/Expressions/MemberAccessExpression.cs
- Cesium.CodeGen/Ir/Expressions/PointerMemberAccessExpression.cs
- Cesium.CodeGen/Ir/Expressions/PrefixIncrementExpression.cs
- Cesium.CodeGen/Ir/Expressions/SetValueExpression.cs
- Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
- Cesium.CodeGen/Ir/Expressions/TypeCastExpression.cs
- Cesium.CodeGen/Ir/Expressions/UnaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueField.cs
- Cesium.CodeGen/Ir/TopLevel/FunctionDefinition.cs
- Cesium.CodeGen/Ir/TopLevel/TopLevelDeclaration.cs
Have to create separate expressions for IValue elements.
> Split emit and declaration scopes

- Cesium.CodeGen/Ir/Expressions/ConstantExpression.cs
Closes #228.
As @kant2002 correctly mentioned, the issue is fixed.
> (#228) ConstantExpression: change the assertion message

- Cesium.IntegrationTests/strings/escape_sequence.ignore.c
> Add test case for string escaping

- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.LogicalAndOperator.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.LogicalOrOperator.verified.txt
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/LogicalBinaryOperatorExpression.cs
- Cesium.Compiler/stdlib/iso646.h
- Cesium.IntegrationTests/stdlib/iso646.c
Also discover issue with incorrect codegen when && or || involved
> Add support for iso646.h

- Cesium.IntegrationTests/Run-Tests.ps1
I noticed that running a single integration test with `Run-Tests -TestCaseName ...` prints `27 tests have been executed successfully` (or whatever the total test count is at the time).
I changed the PowerShell script to instead print the actual number of successful tests (in this case 1).
While I was at it, I also added support for proper singular forms of the sentences in the failed and success cases.
> Fix executed test count for single case run

- Cesium.Parser.Tests/PreprocessorTests/PreprocessorTests.cs
- Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.IfExpressionDefined.verified.txt
- Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.IfExpressionDefinedFunction.verified.txt
- Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.IfExpressionNotDefinedFunction.verified.txt
- Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.IfExpressionNotEqualsSkippedIfNotMetLiteral.verified.txt
- Cesium.Preprocessor/CPreprocessorExpressionParser.cs
- Cesium.Preprocessor/CPreprocessorOperator.cs
- Cesium.Preprocessor/CPreprocessorTokenType.cs
- Cesium.Preprocessor/UnaryExpression.cs
> Add defined preprocessor condition

- Cesium.Ast/Statements.cs
- Cesium.CodeGen.Tests/CodeGenLabelStatementTests.cs
- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenLabelStatementTests.GotoBackwardsDeclaration.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenLabelStatementTests.GotoForwardsDeclaration.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenLabelStatementTests.GotoInsideIf.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenLabelStatementTests.LabelDeclaration.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ReturnWithoutArgument.verified.txt
- Cesium.CodeGen/Contexts/ForScope.cs
- Cesium.CodeGen/Contexts/FunctionScope.cs
- Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
- Cesium.CodeGen/Contexts/IDeclarationScope.cs
- Cesium.CodeGen/Contexts/IEmitScope.cs
- Cesium.CodeGen/Extensions/BlockItemEx.cs
- Cesium.CodeGen/Ir/BlockItems/GoToStatement.cs
- Cesium.CodeGen/Ir/BlockItems/LabelStatement.cs
- Cesium.CodeGen/Ir/BlockItems/ReturnStatement.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/ArithmeticBinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperator.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperatorExpression.cs
- Cesium.IntegrationTests/goto/backward.c
- Cesium.IntegrationTests/goto/forward.c
- Cesium.Parser/CParser.cs
As byproduct fix processing `return;` statement.
Add support for '%' operator.
> Add goto support

- Cesium.Ast/Expressions.cs
- Cesium.CodeGen.Tests/CodeGenOperatorTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.CommaOperator.verified.txt
- Cesium.CodeGen/Extensions/ExpressionEx.cs
- Cesium.CodeGen/Ir/Expressions/CommaExpression.cs
- Cesium.IntegrationTests/comma_operator.c
- Cesium.Parser/CParser.cs
The comma operator can be parsed, and code gen for the resulting comma expression works.
Relates to #207 and #208.
> Add support for comma operator

- Cesium.CodeGen.Tests/Cesium.CodeGen.Tests.csproj
- Cesium.CodeGen.Tests/CliImportTests.cs
- Cesium.CodeGen.Tests/CodeGenArrayTests.cs
- Cesium.CodeGen.Tests/CodeGenBreakStatementTests.cs
- Cesium.CodeGen.Tests/CodeGenForTests.cs
- Cesium.CodeGen.Tests/CodeGenIfTests.cs
- Cesium.CodeGen.Tests/CodeGenLabelStatementTests.cs
- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/CodeGenOperatorTests.cs
- Cesium.CodeGen.Tests/CodeGenPointersTests.cs
- Cesium.CodeGen.Tests/CodeGenTestBase.cs
- Cesium.CodeGen.Tests/CodeGenTypeTests.cs
- Cesium.CodeGen.Tests/MultiFileCompilationTest.cs
- Cesium.CodeGen.Tests/TargetRuntimeTests.cs
- Cesium.CodeGen.Tests/UseInvariantCultureAttribute.cs
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.CanHaveTwoCliImportDeclarations.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.CanHaveTwoFunctionDeclarations.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ImplicitVarargDeclarationCanBeIgnored.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ImplicitVarargDefinitionCanBeIgnored.verified.txt
Big question why we have tests passed without these files present?
> Add missing approved files

- Cesium.IntegrationTests/Cesium.IntegrationTests.proj
This target required for VS otherwise I see error in the Error window
> Add missing target

- Cesium.Ast/Expressions.cs
- Cesium.CodeGen/Extensions/ExpressionEx.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/ArithmeticBinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperator.cs
- Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/PrefixExpression.cs
- Cesium.IntegrationTests/arithmetics.c
- Cesium.Parser.Tests/ParserTests/verified/FullParserTests.PrefixIncrementTest.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_Empty.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_Full.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_MultiLineBody.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_NoInit.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_NoTest.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_NoUpdate.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_OnlyCondition.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_OnlyInit.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ForStatement_OnlyUpdate.verified.txt
- Cesium.Parser/CParser.cs
- Add prefix `--` operator
- Add division `/` operator
> Add missing operators

- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ConsumeUnusedResult.verified.txt
- Cesium.CodeGen/Ir/BlockItems/ExpressionStatement.cs
- Cesium.CodeGen/Ir/Expressions/ConsumeExpression.cs
> Consume result of function call if not needed

- Cesium.Compiler/stdlib/unistd.h
- Cesium.Runtime/ConioFunctions.cs
- Cesium.Runtime/UniStdFunctions.cs
- Cesium.Samples/snake.c
- Cesium.sln
This sample need slightly modified version of sleep, to be able play okayish. Proper C way is to have `nanosleep` which require interop of structs between C and Cesium runtime which is not there yet. I would like to temporary have non-standard `sleep` function, because it allow us to have tech demo
> Add snake sample

- Cesium.Ast/Statements.cs
- Cesium.CodeGen.Tests/CodeGenContinueStatementTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenBreakStatementTests.BreakInFor.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenContinueStatementTests.ContinueInDoWhile.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenContinueStatementTests.ContinueInFor.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenContinueStatementTests.ContinueInWhile.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenForTests.ForTest_NoInit.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenForTests.For_Empty.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenForTests.For_NoTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenForTests.For_NoUpdate.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenForTests.SimpleFor.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenWhileTests.DoWhile.verified.txt
- Cesium.CodeGen/Contexts/FunctionScope.cs
- Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
- Cesium.CodeGen/Contexts/IDeclarationScope.cs
- Cesium.CodeGen/Contexts/LoopScope.cs
- Cesium.CodeGen/Contexts/SwitchScope.cs
- Cesium.CodeGen/Extensions/BlockItemEx.cs
- Cesium.CodeGen/Ir/BlockItems/ContinueStatement.cs
- Cesium.CodeGen/Ir/BlockItems/DoWhileStatement.cs
- Cesium.CodeGen/Ir/BlockItems/ForStatement.cs
- Cesium.CodeGen/Ir/BlockItems/WhileStatement.cs
- Cesium.IntegrationTests/loops/dowhile_with_break.c
- Cesium.IntegrationTests/loops/dowhile_with_continue.c
- Cesium.IntegrationTests/loops/for_with_continue.c
- Cesium.IntegrationTests/loops/while_with_break.c
- Cesium.IntegrationTests/loops/while_with_continue.c
- Cesium.Parser/CParser.cs
> Support continue statement

- Cesium.CodeGen.Tests/CodeGenArrayTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayElementIndexInComparison.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayElementIndexViaVariable.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.GlobalArrayAssignment.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.GlobalMultidimensionalArrayAssignment.verified.txt
- Cesium.CodeGen/Extensions/TranslationUnitEx.cs
- Cesium.CodeGen/Ir/BlockItems/VariableDefinition.cs
- Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs
- Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueIndirection.cs
- Cesium.IntegrationTests/array/array.c
- Cesium.IntegrationTests/array/multidimensional.c
> Add support for global arrays

- Cesium.Compiler/stdlib/unistd.h
- Cesium.IntegrationTests/stdlib/printf.c
- Cesium.Runtime/StdIoFunctions.cs
- Cesium.Runtime/UniStdFunctions.cs
- Cesium.Samples/GOL.c
- Cesium.sln
- Add usleep function
- Add support for %i and %li format in printf
> Add Game of Life sample

- Cesium.CodeGen.Tests/CodeGenOperatorTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.TertiaryOperator.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.TertiaryOperatorWithoutAssignment.verified.txt
- Cesium.CodeGen/Ir/BlockItems/ExpressionStatement.cs
- Cesium.Compiler/stdlib/stdio.h
- Cesium.IntegrationTests/stdlib/printf.c
- Cesium.IntegrationTests/tertiary_operator.c
- Cesium.Runtime/StdIoFunctions.cs
> Printf return int

- Cesium.CodeGen/Contexts/LoopScope.cs
- Cesium.CodeGen/Contexts/SwitchScope.cs
- Cesium.CodeGen/Ir/BlockItems/ForStatement.cs
- Cesium.CodeGen/Ir/BlockItems/SwitchStatement.cs
- Cesium.CodeGen/Ir/BlockItems/WhileStatement.cs
- Cesium.IntegrationTests/loops/for_with_variable.c
- Cesium.IntegrationTests/loops/while_with_variable.c
- Cesium.IntegrationTests/switch/switch_with_fallthrough_variable.c
- Cesium.IntegrationTests/switch/switch_with_variable.c
> Variables in for/while-loops and switch

- Cesium.Compiler/stdlib/stdio.h
- Cesium.Runtime/StdIoFunctions.cs
Previously was implemented as part of #312
Closes #156
> Fix puts signature

- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.TypeDefDeclaration.verified.txt
- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
- Cesium.CodeGen/Ir/BlockItems/FunctionDeclaration.cs
- Cesium.CodeGen/Ir/BlockItems/FunctionDefinition.cs
- Cesium.Compiler/stdlib/stdio.h
- Cesium.Compiler/stdlib/stdlib.h
- Cesium.IntegrationTests/stdlib/test.c
- Cesium.Runtime/CompilerAugmentation.cs
- Cesium.Runtime/StdIoFunctions.cs
This allow implement FILE as opaque handle
Internally it would be index on the internal structure to streams.
> Add typedef resolution in function parameters

- Cesium.Ast/Declarations.cs
- Cesium.CodeGen.Tests/CodeGenArrayTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayInitialization.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.GlobalArrayInitialization.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenPointersTests.AddressOfTest.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ConstCharLiteralDeduplication.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ConstCharLiteralTest.verified.txt
- Cesium.CodeGen/Contexts/AssemblyContext.cs
- Cesium.CodeGen/Extensions/CodeGenEx.cs
- Cesium.CodeGen/Extensions/TranslationUnitEx.cs
- Cesium.CodeGen/Ir/BlockItems/CompoundStatement.cs
- Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
- Cesium.CodeGen/Ir/BlockItems/GlobalVariableDefinition.cs
- Cesium.CodeGen/Ir/Declarations/ScopedDeclarationInfo.cs
- Cesium.CodeGen/Ir/Expressions/ArrayInitializerExpression.cs
- Cesium.CodeGen/Ir/Expressions/CompoundInitializationExpression.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueGlobalVariable.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueLocalVariable.cs
- Cesium.IntegrationTests/array/array_initialization.c
- Cesium.Parser.Tests/ParserTests/DeclarationParserTests.cs
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.ArrayDeclarationWithInitializer.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.ArrayDeclarationWithInitializerWithTrailingComma.verified.txt
- Cesium.Parser/CParser.cs
- Cesium.Runtime/RuntimeHelpers.cs
That's very primitive support for aray initialization, just enough to try first milestone Closes #75
> Basic compound initialization

- Cesium.CodeGen/Contexts/AssemblyContext.cs
- Cesium.CodeGen/Contexts/FunctionScope.cs
- Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
- Cesium.CodeGen/Contexts/IDeclarationScope.cs
- Cesium.CodeGen/Contexts/LoopScope.cs
- Cesium.CodeGen/Contexts/SwitchScope.cs
- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
- Cesium.CodeGen/Contexts/VariableInfo.cs
- Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
- Cesium.CodeGen/Ir/BlockItems/GlobalVariableDefinition.cs
- Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs
- Cesium.IntegrationTests/variable_storage.c
Case when static variable defined in the function does not handled yet.
> Add support for using global static variables

- docs/architecture-sets.md
> Docs: add issue link

- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
- Cesium.Compiler/stdlib/conio.h
- Cesium.Compiler/stdlib/iso646.h
- Cesium.Compiler/stdlib/limits.h
- Cesium.Compiler/stdlib/math.h
- Cesium.Compiler/stdlib/stdbool.h
- Cesium.Compiler/stdlib/stddef.h
- Cesium.Compiler/stdlib/stdio.h
- Cesium.Compiler/stdlib/stdlib.h
- Cesium.Compiler/stdlib/string.h
- Cesium.Compiler/stdlib/unistd.h
- Cesium.IntegrationTests/stdlib/calloc.c
- Cesium.IntegrationTests/stdlib/malloc.c
- Cesium.IntegrationTests/stdlib/system.c
- Cesium.Parser/TokenExtensions.cs
- Cesium.Runtime/StdLibFunctions.cs
- aligned_alloc on NetFx is not supported
- Also add system implementation while I was there.
Depends on #393 to pass calloc.c
> Add functions for memory management

- Cesium.CodeGen.Tests/CodeGenArrayTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.SymmetricArrayAssignment.verified.txt
- Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
- Cesium.sln.DotSettings
> Make subscript operator [] symmetric

- Cesium.Compiler/Compilation.cs
- Cesium.IntegrationTests/IntegrationTestContext.cs
- Cesium.IntegrationTests/IntegrationTestRunner.cs
- Cesium.sln.DotSettings
> Better test parallelization

- docs/architecture-sets.md
> Add link to architecture-sets.md

- Cesium.CodeGen.Tests/CodeGenIncrementDecrementStatementTests.cs
- Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
- Cesium.CodeGen/Ir/BlockItems/AmbiguousBlockItem.cs
- Cesium.CodeGen/Ir/BlockItems/BreakStatement.cs
- Cesium.CodeGen/Ir/BlockItems/GlobalVariableDefinition.cs
- Cesium.CodeGen/Ir/Expressions/ArrayInitializerExpression.cs
- Cesium.CodeGen/Ir/Expressions/CompoundInitializationExpression.cs
- Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
- Cesium.CodeGen/Ir/Expressions/GetAddressValueExpression.cs
- Cesium.CodeGen/Ir/Expressions/StringLiteralListExpression.cs
- Cesium.CodeGen/Ir/Types/InPlaceArrayType.cs
- Cesium.CodeGen/TargetRuntime.cs
- Cesium.Compiler.Tests/CommandLineParsingTest.cs
- Cesium.Compiler/Compilation.cs
- Cesium.Parser/CParser.cs
- Cesium.Parser/TokenExtensions.cs
- Cesium.Preprocessor/BinaryExpression.cs
- Cesium.Preprocessor/CPreprocessorMacroDefinitionParser.cs
- Cesium.Preprocessor/CPreprocessorOperator.cs
- Cesium.Preprocessor/DefinedExpression.cs
- Cesium.Runtime/RuntimeHelpers.cs
Along the way, in the files that were modified by this change, I sealed `internal` classes and simplified `new` expressions
> Removed unused namespaces

- Cesium.CodeGen/Ir/Expressions/CompoundInitializationExpression.cs
Through `if` inversion and block-scoped `using`s
> Removed nesting levels in `CompoundInitializationExpression`

- Cesium.CodeGen.Tests/CodeGenArrayTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayOverPointer.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenArrayTests.PointerArrayIndexing.verified.txt
- Cesium.CodeGen/Ir/Expressions/Values/LValueArrayElement.cs
Example of added pattern
```
argc[i][t]
```
> Allow perform indexing over result of indexing

- Cesium.Compiler/stdlib/stdlib.h
- Cesium.Compiler/stdlib/string.h
- Cesium.IntegrationTests/stdlib/program/getenv.c
- Cesium.IntegrationTests/stdlib/string/byte/strchr.c
- Cesium.Runtime/StdIoFunctions.cs
- Cesium.Runtime/StdLibFunctions.cs
- Cesium.Runtime/StringFunctions.cs
> Add getenv and strchr

- Cesium.CodeGen.Tests/CodeGenEnumTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenEnumTests.EnumInFuncionCall.verified.txt
- Cesium.CodeGen.Tests/verified/CodeGenEnumTests.EnumViaTypeDef.verified.txt
- Cesium.CodeGen/Extensions/TranslationUnitEx.cs
- Cesium.CodeGen/Ir/Expressions/TypeCastExpression.cs
Allow enums values to be used when defined via typedef
Allow passing enum values to functions
> Improve enum resolutions

- Cesium.CodeGen.Tests/CodeGenSizeofTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenSizeofTests.GlobalStructSizeof.verified.txt
- Cesium.CodeGen/Ir/Expressions/ExpressionSizeOfOperatorExpression.cs
- Cesium.CodeGen/Ir/Expressions/SizeOfOperatorExpression.cs
> Resolve sizeof on global struct definitions

- Cesium.CodeGen.Tests/CodeGenMethodTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenMethodTests.UnaryPlusAndStart.verified.txt
- Cesium.CodeGen/Ir/Expressions/UnaryOperator.cs
- Cesium.CodeGen/Ir/Expressions/UnaryOperatorExpression.cs
- Cesium.IntegrationTests/some_unaryops.c
- Cesium.Parser/CParser.cs
Also, unary plus is now supported. I've added two tests with it.
> Add unary plus

- Cesium.CodeGen/Extensions/TypeSystemEx.cs
- Cesium.CodeGen/Ir/Expressions/TypeCastExpression.cs
- Cesium.CodeGen/Ir/Types/CTypeSystem.cs
- Cesium.IntegrationTests/type_casts.c
Without that assert macro does not working.
> Add support for unsigned type alias

- Cesium.CodeGen.Tests/CodeGenPointersTests.cs
- Cesium.CodeGen/Contexts/AssemblyContext.cs
- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
- Cesium.CodeGen/Ir/Types/PointerType.cs
in two separate translation units
> Allow use types from header

- Cesium.Ast/Declarations.cs
- Cesium.CodeGen.Tests/CodeGenTestBase.cs
- Cesium.CodeGen/CompilationOptions.cs
- Cesium.Compiler/Arguments.cs
- Cesium.Compiler/AstDumper.cs
- Cesium.Compiler/CommandLineParser.cs
- Cesium.Compiler/Compilation.cs
- Cesium.Compiler/IndentedTextWriter.cs
- Cesium.Compiler/Main.cs
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.EnumDeclaration.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.EnumTypeDef.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.EnumTypeDefTrailingComma.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.EnumVariableDeclaration.verified.txt
I choose not JSON, to have more dense format, since JSON too sparse to navigate.
> Add option to dump AST

- Cesium.Ast/Expressions.cs
- Cesium.Parser.Tests/ParserTests/DeclarationParserTests.cs
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.CompoundStructInitializer.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.InitializerWithCast.verified.txt
- Cesium.Parser.Tests/ParserTests/verified/DeclarationParserTests.InitializerWithCastAddAddress.verified.txt
- Cesium.Parser/CParser.cs
Also improve parser to closer match C spec
Related #207
> Add parsing compound literal expressions

- Cesium.CodeGen/Extensions/TranslationUnitEx.cs
- Cesium.CodeGen/Ir/BlockItems/GlobalVariableDefinition.cs
- Cesium.CodeGen/Ir/Emitting/BlockItemEmitting.cs
- Cesium.CodeGen/Ir/Expressions/Values/LValueField.cs
- Cesium.CodeGen/Ir/Lowering/BlockItemLowering.cs
That allow us have same codepath for functions initialization and for global initialization
> Separate global declaration from initialization

- Cesium.Parser.Tests/PreprocessorTests/PreprocessorTests.cs
- Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.IfExpressionNotDefinedInsideComplexExpressionFunction.verified.txt
- Cesium.Preprocessor/ConditionExpressions/CPreprocessorExpressionParser.cs
- Cesium.Preprocessor/ConditionExpressions/ConditionalExpression.cs
> Fix stack overflow in the preprocessor on complex expressions

- Cesium.CodeGen.Tests/CodeGenTypeTests.cs
- Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ResolutionOfRecursiveTypes.verified.txt
- Cesium.CodeGen/Contexts/TranslationUnitContext.cs
> Fix case of recursive type resolution

- Cesium.Compiler/stdlib/stdio.h
- Cesium.IntegrationTests/stdlib/io/fscanf.c
- Cesium.Runtime.Tests/Cesium.Runtime.Tests.csproj
- Cesium.Runtime.Tests/StdIoFunctionTests.cs
- Cesium.Runtime/Cesium.Runtime.csproj
- Cesium.Runtime/StdIoFunctions.cs
- Directory.Packages.props
Most of the features of the `scanf` function have been implemented. Added new tests for `scanf`
> Implement scanf

- Cesium.CodeGen/Ir/Expressions/TypeCastExpression.cs
- Cesium.CodeGen/Ir/Types/CTypeSystem.cs
Encounter during testing with https://github.com/csmith-project/csmith
> Add conversion to long long

- Cesium.CodeGen/Ir/Expressions/Constants/IntegerConstant.cs
- Cesium.Compiler/stdlib/limits.h
- Cesium.Compiler/stdlib/stdint.h
- Cesium.IntegrationTests/stdlib/types/limits.c
- Cesium.Runtime.Tests/StdIoFunctionTests.cs
- Directory.Packages.props
Most important part of this change was adding support for numerals with typed suffixes.
> Add limits.h

- Cesium.Compiler/stdlib/float.h
- Cesium.Compiler/stdlib/math.h
- Cesium.Compiler/stdlib/time.h
- Cesium.Runtime/MathFunctions.cs
- Cesium.Runtime/TimeFunctions.cs
Math functions on float number implemented using their double variant in .NET Standard 2.0
> Improve stdlibrary with time and math functions

- CONTRIBUTING.md
- Cesium.Ast/Cesium.Ast.csproj
- Cesium.CodeGen.Tests/Cesium.CodeGen.Tests.csproj
- Cesium.CodeGen.Tests/CodeGenNetInteropTests.cs
- Cesium.CodeGen/Cesium.CodeGen.csproj
- Cesium.Compiler.Tests/Cesium.Compiler.Tests.csproj
- Cesium.Compiler/Cesium.Compiler.csproj
- Cesium.Compiler/RuntimeConfig.cs
- Cesium.Core/Cesium.Core.csproj
- Cesium.IntegrationTests/Cesium.IntegrationTests.csproj
- Cesium.Parser.Tests/Cesium.Parser.Tests.csproj
- Cesium.Parser/Cesium.Parser.csproj
- Cesium.Preprocessor/Cesium.Preprocessor.csproj
- Cesium.Runtime.Tests/Cesium.Runtime.Tests.csproj
- Cesium.Sdk.Tests/Cesium.Sdk.Tests.csproj
- Cesium.Solution.Metadata/Cesium.Solution.Metadata.csproj
- Cesium.TestFramework.Tests/Cesium.TestFramework.Tests.csproj
- Cesium.TestFramework/CSharpCompilationUtil.cs
- Cesium.TestFramework/Cesium.TestFramework.csproj
- Cesium.sln
- build/_build.csproj
- global.json
Otherwise, something seems wrong on the CI.
> Update build to .NET 9

- CHANGELOG.md
- Cesium.Sdk/Sdk/Sdk.props
- Cesium.Templates/content/Cesium.Template.App/.template.config/template.json
- Cesium.Templates/content/Cesium.Template.App/MyProject.Name.ceproj
- Cesium.Templates/content/Cesium.Template.Library/.template.config/template.json
- Cesium.Templates/content/Cesium.Template.Library/MyProject.Name.ceproj
- Directory.Build.props
- README.md
- docs/msbuild-sdk.md
- scripts/Update-Version.ps1
Also, improve documentation.
And release v0.1.2.
Closes #849.
> Templates: drop the default item duplicates
