Cesium.CodeGen.Tests/CodeGenTests.DefaultedFrameworkTest.verified.txt
Cesium.CodeGen.Tests/CodeGenTests.FrameworkTest_targetFramework=SystemRuntime_versionString=4.2.2.0.verified.txt
Cesium.CodeGen.Tests/CodeGenTests.FrameworkTest_targetFramework=mscorlib_versionString=4.0.0.0.verified.txt
Cesium.CodeGen.Tests/CodeGenTests.FrameworkTest_targetFramework=netstandard_versionString=2.1.0.0.verified.txt
Cesium.CodeGen.Tests/CodeGenTests.cs
Cesium.CodeGen/Generator.cs

I tried implementing #10 .
```csharp
public enum TargetFrameworks
{
mscorlib,
SystemRuntime,
netstandard,
}
public record TargetRuntimeIdentifier(
TargetFrameworks targetFramework,
Version version);
public static AssemblyDefinition GenerateAssembly(
TranslationUnit translationUnit,
AssemblyNameDefinition name,
ModuleKind kind,
TargetRuntimeIdentifier? targetRuntime = default) { ... }
```
`TargetRuntimeIdentifier` is producing our target framework identity to cecil.
Defaulted target framework (`default`) is netstandard2.1 .
Is issue right for meaning it?

Supported different target frameworks

---

Cesium.IntegrationTests/Run-Tests.ps1

Turns out that, by default, PowerShell will pipe the stdout from the called binaries to the function's return values. This means that our compilation functions were returning the stdout plus the last bool value.
The caller was interpreting the resulting non-empty arrays as truthy, and wasn't properly calculating the test states.

IntegrationTests: prevent false positives

---

Cesium.Compiler/Program.cs
Cesium.IntegrationTests/Cesium.IntegrationTests.proj
Cesium.IntegrationTests/empty_include.c

Right now includes works a bit strange. I assume that `""` resolution should start from location of main compilation file, not from current directory.

Tests include path resolution

---

Cesium.CodeGen.Tests/CodeGenTestBase.cs
Cesium.CodeGen/Contexts/AssemblyContext.cs
Cesium.CodeGen/Contexts/TranslationUnitContext.cs
Cesium.CodeGen/Extensions/TypeSystemEx.cs
Cesium.CodeGen/Generators/Assemblies.cs
Cesium.Compiler/Program.cs

I put list of assemblies for resolving CLI import in the `TranslationUnitContext`. I need this for basic runtime library support, since resolution should happens from runtime library, and I do not want to use `Assembly.GetReferencesAssemblies()` purely, because then I cannot run this compiler via NativeAOT.
Other benefit, is that way we explicitly control list of assemblies to resolve CLI import and then this can be controller by developer via command line arguments.

Let compiler decide list assemblies for CLI import

---

.github/workflows/integration-tests.yml
Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/CodeGenTestBase.cs
Cesium.CodeGen.Tests/CodeGenTypeTests.FunctionForwardDeclaration.received.txt
Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen/Contexts/FunctionScope.cs
Cesium.CodeGen/Contexts/Meta/FunctionInfo.cs
Cesium.CodeGen/Contexts/TranslationUnitContext.cs
Cesium.CodeGen/Extensions/CodeGenEx.cs
Cesium.CodeGen/Extensions/TypeDefinitionEx.cs
Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
Cesium.CodeGen/Ir/DeclarationInfo.cs
Cesium.CodeGen/Ir/Expressions/Constants/CharConstant.cs
Cesium.CodeGen/Ir/Expressions/Constants/IConstant.cs
Cesium.CodeGen/Ir/Expressions/Constants/StringConstant.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.CodeGen/Ir/Expressions/IdentifierConstantExpression.cs
Cesium.CodeGen/Ir/ParametersInfo.cs
Cesium.CodeGen/Ir/TopLevel/FunctionDefinition.cs
Cesium.CodeGen/Ir/TopLevel/SymbolDeclaration.cs
Cesium.CodeGen/Ir/Types/ConstType.cs

This is a part of #69.
This only adds support for the internal linkage (i.e. inside of a translation unit, not between different ones).

(#69) CodeGen: internal linkage function declaration support

---

Cesium.CodeGen.Tests/CodeGenMethodTests.PointerReceivingFunction.verified.txt
Cesium.CodeGen.Tests/CodeGenTypeTests.EmptyFunctionDeclaration.verified.txt
Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen/Ir/TopLevel/FunctionDefinition.cs
Cesium.IntegrationTests/functions.c

Fix codegen for empty functions without any statement. Inside IL they are require to have at least one `ret`  instruction inside method body.

Add more test cases for function signatures

---

Cesium.Ast/Expressions.cs
Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.AddressOfTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructUsageWithPointerMemberAccessGet.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructUsageWithPointerMemberAccessSet.verified.txt
Cesium.CodeGen/Extensions/ExpressionEx.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs
Cesium.CodeGen/Ir/Expressions/LValues/ILValue.cs
Cesium.CodeGen/Ir/Expressions/LValues/LValueArrayElement.cs
Cesium.CodeGen/Ir/Expressions/LValues/LValueField.cs
Cesium.CodeGen/Ir/Expressions/LValues/LValueLocalVariable.cs
Cesium.CodeGen/Ir/Expressions/LValues/LValueParameter.cs
Cesium.CodeGen/Ir/Expressions/PointerMemberAccessExpression.cs
Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
Cesium.CodeGen/Ir/Expressions/UnaryOperator.cs
Cesium.CodeGen/Ir/Expressions/UnaryOperatorExpression.cs
Cesium.IntegrationTests/structs.c
Cesium.Parser.Tests/ParserTests/FullParserTests.cs
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.AddressOfTest.verified.txt
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.StructUsageWithPointerMemberAccessGet.verified.txt
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.StructUsageWithPointerMemberAccessSet.verified.txt
Cesium.Parser/CParser.cs
Cesium.Samples/structs.c

Short example:
```c
typedef struct { int x; } foo;
int main(void) 
{ 
foo y; 
foo *z; 
z = &y; 
z->x = 42; 
return z->x; 
}
```
TODO:

Pointer member access and address-of operator

---

Cesium.Compiler/Main.cs

In current implementation available values for enum type arguments do not show in help
```
Cesium.Compiler 0.0.0
Copyright (C) 2022 Cesium.Compiler
-o, --out       Required.
--framework     (Default: Net)
--nologo        Suppress compiler banner message
...
```
changed to
```
Cesium.Compiler 0.0.0
Copyright (C) 2022 Cesium.Compiler
-o, --out       Required.
--framework     (Default: Net)  Valid values: Net, NetFramework, NetStandard
--nologo        Suppress compiler banner message
...

Help enum values

---

Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructAddressWithPointerMemberAccessGet.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructAddressWithPointerMemberAccessSet.verified.txt
Cesium.CodeGen/Ir/Expressions/AssignmentExpression.cs
Cesium.CodeGen/Ir/Expressions/BinaryOperatorExpression.cs
Cesium.CodeGen/Ir/Expressions/ConstantExpression.cs
Cesium.CodeGen/Ir/Expressions/Constants/CharConstant.cs
Cesium.CodeGen/Ir/Expressions/Constants/IConstant.cs
Cesium.CodeGen/Ir/Expressions/Constants/IntegerConstant.cs
Cesium.CodeGen/Ir/Expressions/Constants/StringConstant.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.CodeGen/Ir/Expressions/IExpression.cs
Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs
Cesium.CodeGen/Ir/Expressions/LValues/LValueField.cs
Cesium.CodeGen/Ir/Expressions/LogicalBinaryOperatorExpression.cs
Cesium.CodeGen/Ir/Expressions/PointerMemberAccessExpression.cs
Cesium.CodeGen/Ir/Expressions/PrefixIncrementExpression.cs
Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
Cesium.CodeGen/Ir/Expressions/UnaryOperatorExpression.cs
Cesium.Parser.Tests/ParserTests/FullParserTests.cs
Cesium.Parser.Tests/ParserTests/StatementParserTests.cs
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.StructAddressWithPointerMemberAccessGet.verified.txt
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.StructAddressWithPointerMemberAccessSet.verified.txt
Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.AddressOfInParens.verified.txt
Cesium.Parser/CParser.cs
Cesium.Samples/structs.c

For now pointer member access operator (#129) works only for lvalues, but not rvalues. E.g. this sample doesn't compile:
```c
foo x;
(&x)->x = 42; // error
```
In #129 to find members by identifier we relied on `GetValueType: unit -> TypeReference` method implemented for all lvalues. I propose to extend this approach and track type information for all IR expressions:
```c
foo x;
// `x` is lvalue expression of type `foo`
// `(&x)` is rvalue expression of type `foo*`
// `(&x)->x` is lvalue expression of type `int`
(&x)->x = 42; // works!
(42)->x = 42; // error: "Int32" has no member named "x"
```
- ~Implement `GetExpessionType` for binary operator expressions~ See #136

Track type information for IR expressions

---

Cesium.Ast/Expressions.cs
Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructUsageWithMemberAccessGet.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructUsageWithMemberAccessSet.verified.txt
Cesium.CodeGen/Extensions/ExpressionEx.cs
Cesium.CodeGen/Ir/Expressions/MemberAccessExpression.cs
Cesium.CodeGen/Ir/Expressions/PointerMemberAccessExpression.cs
Cesium.Parser.Tests/ParserTests/FullParserTests.cs
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.StructUsageWithMemberAccessGet.verified.txt
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.StructUsageWithMemberAccessSet.verified.txt
Cesium.Parser/CParser.cs

Member access operator is basically combination of `&` and `->`, so I use lowering to already existing expressions.
Closes #138

(#138) Implement member access operator (`.`)

---

Cesium.CodeGen.Tests/verified/CodeGenForTests.ForTest_NoInit.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.For_Empty.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.For_NoTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.For_NoUpdate.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.SimpleFor.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfElseTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.Arithmetic.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.AssigmentLoweringTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.BitOrAssignmentLoweringTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.PostfixIncrementTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.SimpleVariableTest.verified.txt
Cesium.CodeGen/Ir/Expressions/LValues/LValueLocalVariable.cs

Before:
``` csharp
value.EmitTo(scope);
scope.StLoc(_definition);
```
After:
``` csharp
value.EmitTo(scope);
scope.Method.Body.Instructions.Add(_definition.Index switch
{
0 => Instruction.Create(OpCodes.Stloc_0),
1 => Instruction.Create(OpCodes.Stloc_1),
2 => Instruction.Create(OpCodes.Stloc_2),
3 => Instruction.Create(OpCodes.Stloc_3),
<= sbyte.MaxValue => Instruction.Create(OpCodes.Stloc_S, _definition),
_ => Instruction.Create(OpCodes.Stloc, _definition)
});
```

Local variable set optimization

---

Cesium.IntegrationTests/functions.c
Cesium.IntegrationTests/structs_nested.c

Test that accessing nested fields work
I did not see that `.` access was tests in the structs somewhere
Also test second variant of forward declaraions

More integration testing

---

Cesium.CodeGen.Tests/Cesium.CodeGen.Tests.csproj
Cesium.CodeGen.Tests/CodeGenTestBase.cs
Cesium.CodeGen/Cesium.CodeGen.csproj
Cesium.CodeGen/Contexts/AssemblyContext.cs
Cesium.CodeGen/Extensions/TypeDefinitionEx.cs
Cesium.CodeGen/Extensions/TypeSystemEx.cs
Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
Cesium.CodeGen/Ir/TopLevel/FunctionDefinition.cs
Cesium.CodeGen/Ir/Types/InPlaceArrayType.cs
Cesium.CodeGen/Ir/Types/StructType.cs
Cesium.Compiler/Compilation.cs

Reduce usage of `typeof` and Reflection across codebase
I did not change all usages, since some of them require factoring code differently, and it produce much more noise, and would be hard to review
**Notes from F.:**
Closes #161.

Center type and method importation around Cecil

---

Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.AmbiguousCallTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.Arithmetic.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.NegationExpressTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ConstIntMinLiteralTest.verified.txt
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.AbsCallTest.verified.txt
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.NegationTest.verified.txt
Cesium.Parser/CParser.cs

Parse INT_MIN value properly
Right now I belive bug is in the tokenizer which parse `-34` as `-` (unary negation) and `34` (constant). That triggers bug in the lowering when we try to parse `-2147483648` and parse `2147483648` as integer, which is impossible.

Parse INT_MIN value properly

---

Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen/Ir/Expressions/PointerMemberAccessExpression.cs

(#198) PointerMemberAccessExpression: get rid of redundant catch

---

scripts/approve-all.ps1

I know for a fact that there is a person who tried to run `approve-all.ps1` script by copy-pasting it's code in PowerShell shell :grinning: The script by default relies on `$PSScriptRoot` variable, but PowerShell populates it only when running in script mode, i.e. 
`> powershell -c approve-all.ps1`. Otherwise, this variable is empty, and `$SolutionRoot` variable becomes `"/.."`.  As a result `Get-ChildItem` scans the whole disk recursively in search of  "*.received.txt" files which can be quite dangerous.
With this PR I try to detect cases when `$PSScriptRoot` has no meaningful value, warn user about it and essentially prevent execution of search.
As far as I know, aforementioned person had troubles with configuration of execution policy. Maybe it also makes sense to modify command in the …

Warn when running approve-all.ps1 not in script mode

---

Cesium.Compiler/Cesium.Compiler.csproj
Cesium.Compiler/stdlib/math.h
Cesium.Compiler/stdlib/stdio.h
Cesium.IntegrationTests/arithmetics_overflow.ignore.c
Cesium.IntegrationTests/array_pointer.ignore.c
Cesium.IntegrationTests/atexit.ignore.c
Cesium.IntegrationTests/const_variables.c
Cesium.IntegrationTests/function_ptr.ignore.c
Cesium.IntegrationTests/if_condition.c
Cesium.IntegrationTests/stack_access.ignore.c
Cesium.IntegrationTests/stdlib/abs.c
Cesium.IntegrationTests/stdlib/printf.c
Cesium.IntegrationTests/struct_subscription.ignore.c
Cesium.IntegrationTests/tertiary_operator.ignore.c
Cesium.IntegrationTests/test.c
Cesium.Runtime/StdLibFunctions.cs

- Add both working, and not yet working snippets of C
- Add support for recursive dir traversal in integration testing. Will need this for more tests to C runtime

Add bunch of test cases

---

Cesium.Compiler/Cesium.Compiler.csproj
Directory.Build.props
README.md

This produces executable which can be packed into SDK + tools Nugets.
I move version management to shared `Directory.Build.props` so versioning would apply to all projects.
Also I use `VersionPrefix` so it would be easier for us to add custom suffix in automated fashion. For example add `--version-suffix ci-123` will produce `0.0.1-ci-123` version.
Bump version to 0.0.1, for SDK+tools I would like to have at least some version.

Document publish process for Cesium

---

Cesium.Parser.Tests/PreprocessorTests/PreprocessorTests.cs
Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.IfElseLiteral.verified.txt
Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.NestedIfDefined.verified.txt
Cesium.Preprocessor/CPreprocessor.cs

Extend limits with signed/unsigned char options. By default MSVC/GCC/LLVM use signed char and you can enable unisnged char if you like using switch.
We can expose `-funsigned-char` switch using command line option afterwards.
Closes #250

Add support for #else directive

---

Cesium.Compiler/Compilation.cs

Before that compilation carash during copy of Cesium.Runtime.dll
Also copy not Cesium.Runtime which sit near compiler, but one which specified in command line

Allow produce compilation output in same folder as Cesium

---

Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.FloatConstTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.FloatConstTest2.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.PrimitiveTypes.verified.txt
Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
Cesium.CodeGen/Ir/Expressions/AssignmentExpression.cs
Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperatorExpression.cs
Cesium.CodeGen/Ir/Expressions/ConstantExpression.cs
Cesium.CodeGen/Ir/Expressions/Constants/FloatingPointConstant.cs
Cesium.CodeGen/Ir/Expressions/TypeCastExpression.cs
Cesium.CodeGen/Ir/Types/CTypeSystem.cs
Cesium.IntegrationTests/float.c
Cesium.Parser.Tests/ParserTests/FullParserTests.cs
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.FloatingPointLiteral.verified.txt

- Make typecast explicit operation in the IR.
- Due to fact that `IDeclarationScope` is inaccessible during Lower call. I put explicit typecasts during emit phase. That require subsequet changes in `IExpression` interface and possible in the `ToIntermediate` as well.
- `BinaryOperatorExpression.EmitConversion` consult now `CTypeSystem`, I plan to remove that method altogether and replace it by insertion of corresponding `TypeCastExpression` when needed.
- Changes in `PrimitiveTypes` test is artifact of typecast insertion. Once constant evaluation would start appearing, I expect changes in these area again. Same for `FloatConstTest2`, it will emit ldc.r4 becasue `(float)1.5` would be folded directly to `1.5f`
I did not close #246 with that PR because I need to invest in more tests for …

Add typecast expression

---

Cesium.CodeGen.Tests/CodeGenTestBase.cs
Cesium.CodeGen/Contexts/AssemblyContext.cs
Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
Cesium.CodeGen/Contexts/TranslationUnitContext.cs
Cesium.CodeGen/Extensions/TranslationUnitEx.cs
Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
Cesium.CodeGen/Ir/BlockItems/TypeDefBlockItem.cs
Cesium.CodeGen/Ir/TopLevel/TopLevelDeclaration.cs
Cesium.Compiler/Compilation.cs

IDeclarationScope is internal, so I have to shake code a bit.
Lazy instantiation of global initialization method needed if I want to have lowering, otherwise that produce noise in the tests.
Actual addition of lowering is blocked by fact that decarations and ITopNode tightly coupled, so I cannot extract one simple thing.
Also create BlockItem node for TypeDef declarations. That step towards #214, and most likely allow have NamedTypes to point to real types, and not type names of the CLR projection

TypeDef as block item

---

Cesium.CodeGen/Ir/Declarations/LocalDeclarationInfo.cs
Cesium.Compiler/stdlib/stddef.h

- exposes nint type. That's Cesium specific type which maps to `System.IntPtr`. That allow implement `ptrdiff_t`, `intptr_t` and `uintptr_t` in unified manner.
- `offsetof` does not implemented. See #276

Add declarations for stddef.h

---

Cesium.CodeGen/Extensions/CodeGenEx.cs
Cesium.CodeGen/Extensions/TypeSystemEx.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.Compiler/stdlib/stdio.h
Cesium.IntegrationTests/stdlib/printf.c
Cesium.Parser/TokenExtensions.cs
Cesium.Runtime/StdIoFunctions.cs

For now only char* arguments supported. Cannot do much with integers, since during emit phase I have lost information about expression type, and I cannot imagin what kind of IR node I need to preserve that, and at the same time do not overcomplicate things. Related to #196

Primitive support for varargs

---

Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.VarargCall.verified.txt
Cesium.CodeGen/Contexts/Meta/FunctionInfo.cs
Cesium.CodeGen/Extensions/CodeGenEx.cs
Cesium.CodeGen/Extensions/TypeDefinitionEx.cs
Cesium.CodeGen/Extensions/TypeSystemEx.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.IntegrationTests/stdlib/printf.c
Cesium.Runtime/StdIoFunctions.cs

When invoke function annotated as vararg, created local buffer for the variable arguments. For each argument currently allocated 8 bytes. This should be enough for most common usage.

Pass varargs via stack allocated buffer

---

Cesium.Compiler/Main.cs

close #264 
This is why it work, code of AutoBuild:
```csharp
public static HelpText AutoBuild<T>(ParserResult<T> parserResult, Func<HelpText, HelpText> onError, int maxDisplayWidth = DefaultMaximumLength)
{
if (parserResult.Tag != ParserResultType.NotParsed)
throw new ArgumentException("Excepting NotParsed<T> type.", "parserResult");
var errors = ((NotParsed<T>)parserResult).Errors;
if (errors.Any(e => e.Tag == ErrorType.VersionRequestedError))
return new HelpText($"{HeadingInfo.Default}{Environment.NewLine}") { MaximumDisplayWidth = maxDisplayWidth }.AddPreOptionsLine(Environment.NewLine);
```
So they handle ErrorType.VersionRequestedError and use build-in logic for formatting version.

Support version command

---

Cesium.IntegrationTests/strings/escape_sequence.c
Cesium.Parser/TokenExtensions.cs

String escape sequence support

---

Cesium.Ast/Expressions.cs
Cesium.CodeGen.Tests/CodeGenOperatorTests.cs
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.ConditionalFloatAndInt.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.ConditionalInt.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.ConditionalVoid.verified.txt
Cesium.CodeGen/Extensions/ExpressionEx.cs
Cesium.CodeGen/Ir/Expressions/ConditionalExpression.cs
Cesium.CodeGen/Ir/Types/CTypeSystem.cs
Cesium.IntegrationTests/tertiary_operator.c
Cesium.IntegrationTests/tertiary_operator.ignore.c
Cesium.Parser.Tests/ParserTests/StatementParserTests.cs
Cesium.Parser.Tests/ParserTests/verified/StatementParserTests.ConditionalOperator.verified.txt
Cesium.Parser/CParser.cs

Conditional expressions can be parsed and code generation works, but only for arithmetic types and the void type.
Relates to #207 and #208.
These cases from 6.5.15 are not yet supported (because I don't know how to properly handle these cases):
* both operands have the same structure or union type
* both operands are pointers to qualified or unqualified versions of compatible types
* one operand is a pointer and the other is a null pointer constant
* one operand is a pointer to an object type and the other is a pointer to a qualified or unqualified version of `void`

Add initial support for conditional expressions

---

Cesium.CodeGen/Ir/Expressions/GetAddressValueExpression.cs

While working pointer support for #297, I believe I discovered a bug in `GetAddressValueExpression`. The type of the expression was the type of the value the address was taken of, but it should be a pointer to the type of the value.

Fix type of GetAddressValueExpression

---

Cesium.CodeGen/Contexts/IDeclarationScope.cs

Otherwise, `CompilationException` doesn't get resolved in the XML documentation.

IDeclarationScope: add a using to import CompilationException

---

Cesium.CodeGen.Tests/verified/CodeGenForTests.ForTest_NoInit.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.For_Empty.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.For_NoTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.For_NoUpdate.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenForTests.SimpleFor.verified.txt
Cesium.CodeGen/Contexts/ForScope.cs
Cesium.CodeGen/Contexts/FunctionScope.cs
Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
Cesium.CodeGen/Contexts/IDeclarationScope.cs
Cesium.CodeGen/Contexts/LoopScope.cs
Cesium.CodeGen/Ir/BlockItems/AmbiguousBlockItem.cs
Cesium.CodeGen/Ir/BlockItems/BreakStatement.cs
Cesium.CodeGen/Ir/BlockItems/ForStatement.cs
Cesium.CodeGen/Ir/BlockItems/GoToStatement.cs
Cesium.CodeGen/Ir/BlockItems/LabelStatement.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs

Declaration scopes inherently hierarchical, and we need to preserve that hierarchy. By exposing separate dictionaries we show too much of internal structure, even if all we need is resolve identifier, and know what kind of identifier it is. For example GlobalFields and Variables is essentially the same, except they are declared in different scopes. This is mostly not important until emit phase.
Rework for statement to not rely on `EndInstruction`
That makes emit scopes hierarchical, but we really want to have declaration scopes as hierarchical.

Prepare for refactoring of declaration scopes

---

Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.ComplexStructDefinition.verified.txt
Cesium.CodeGen/Ir/Declarations/LocalDeclarationInfo.cs
Cesium.CodeGen/Ir/ParametersInfo.cs

- Closes #234.
- Closes #72.
- Leads to #332.

Parameter abstract declarators

---

Cesium.CodeGen.Tests/verified/CodeGenArrayTests.GlobalArrayAssignment.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.GlobalMultidimensionalArrayAssignment.verified.txt
Cesium.CodeGen/Ir/Types/InPlaceArrayType.cs
Cesium.Runtime.Tests/Cesium.Runtime.Tests.csproj
Cesium.Runtime.Tests/RuntimeHelpersTests.cs
Cesium.Runtime.Tests/Usings.cs
Cesium.Runtime/RuntimeHelpers.cs
Cesium.sln
Directory.Build.props

In previous PR I allocate global array variables using localalloc in the module constructor. That's obviously does not work, but small integration tests does nto catch that. Only after I start running GOL I discover that issue. For now I allocate on the heap and only in .NET 6 configuration. following issues
- Provide netstandard implementation for memory allocation (basically port NativeMemory)
- Codegen for memory deallocation if module is unloaded.
**After merge (F):**

Allocate global array variables on the heap

---

Cesium.Compiler/Arguments.cs

For now this parameters do nothing. If we accept them even if we do nothing, that simplify using Cesium when invoking from Make. For example you can CC=/usr/bin/cesium and let Make do it's magic. Eventually

Accept O3 and Wall

---

Cesium.CodeGen.Tests/verified/CodeGenMethodTests.StandardMain.verified.txt
Cesium.CodeGen/Ir/BlockItems/FunctionDefinition.cs
Cesium.IntegrationTests/array/multidimensional.c
Cesium.Runtime/RuntimeHelpers.cs

- varible b has incorrect dimensions leading to out of bounds error
- syntetic entry point do not cleaunp args
- and fix string allocation, if we have non-English parameters we can truncate args

Fix failing multidimecional.c test

---

.github/workflows/run-build-and-integration-tests.yml
Cesium.CodeGen.Tests/TargetRuntimeTests.cs
Cesium.CodeGen.Tests/verified/TargetRuntimeTests.DefaultedFrameworkTest.verified.txt
Cesium.CodeGen.Tests/verified/TargetRuntimeTests.FrameworkTest_targetFramework=MsCorLib_systemAssemblyVersionString=4.0.0.0_frameworkVersionString=4.8.verified.txt
Cesium.CodeGen.Tests/verified/TargetRuntimeTests.FrameworkTest_targetFramework=NetStandard_systemAssemblyVersionString=2.1.0.0_frameworkVersionString=2.1.verified.txt
Cesium.CodeGen.Tests/verified/TargetRuntimeTests.FrameworkTest_targetFramework=SystemRuntime_systemAssemblyVersionString=4.2.2.0_frameworkVersionString=6.0.verified.txt
Cesium.CodeGen/Contexts/AssemblyContext.cs
Cesium.CodeGen/Contexts/TranslationUnitContext.cs
Cesium.CodeGen/Extensions/TypeSystemEx.cs
Cesium.CodeGen/Ir/Types/InPlaceArrayType.cs
Cesium.CodeGen/TargetRuntime.cs
Cesium.IntegrationTests/Run-Tests.ps1

which was broken for a long time. Because compiler run under TFM net7.0 we canot use `ImportReference(typeof(XXX))` or `ImportReference(typeof(XXX).GetMethod("mymethod"))` since that will bring depedency on S.P.CoreLib to finnal executable, which does not exists in .NET Framework.
Also add another test leg to make sure that it would not regress in the future.
I remove one line in test [/TargetRuntimeTests.cs](https://github.com/ForNeVeR/Cesium/pull/385/files#diff-0b3c15c70dd4a60cb9e5b2a48f0e890eb58fc8dee48810c6f4bc9b20ba043722) because I do not sure what it test since CoreLib is always S.P.CoreLib and after I fix resolving, it always mscorlib due to some Cecil internal stuff.
Also if you run `pwsh -c .\Cesium.IntegrationTests\Run-Tests.ps1 -TestCaseName structs\struct_subscription.c …

Fix compilation for .NET Framework

---

Cesium.CodeGen.Tests/CodeGenPointersTests.cs
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayAddressOf.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ValidPointerSubtractionTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenPointersTests.CanUseBuiltinOffsetOfOnBothDeclaredAndStruct.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenPointersTests.CanUseBuiltinOffsetOfOnDeclaredStruct.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenPointersTests.CanUseBuiltinOffsetOfOnDeepMembers.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenPointersTests.CanUseBuiltinOffsetOfOnTaggedStruct.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenPointersTests.CanUseOffsetOfInstanceOnDeclaredStruct.verified.txt
Cesium.CodeGen/Ir/BlockItems/TypeDefBlockItem.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.CodeGen/Ir/Expressions/InstanceForOffsetOfExpression.cs
Cesium.CodeGen/Ir/Expressions/TypeCastExpression.cs
Cesium.CodeGen/Ir/Expressions/UnaryOperatorExpression.cs
Cesium.Compiler/stdlib/stddef.h
Cesium.IntegrationTests/pointers/pointers_offsetof.c
Cesium.sln
Cesium.sln.DotSettings
README.md
docs/builtins.md

Closes #276.
Replacement for #374 - I decided to make it different PR as the implementation differs largely.
This implementation introduces builtin to obtain ptr to dirty instance of arbitrary struct.
This allows to write macro appropriate to offsetof features that previous implementation was unable to cover.
For example, `offsetof(foo, bar.baz)` now works.
This PR also uncovers discrepancy between default .net struct layout and msvc struct layout - I was forced to use Sequential struct layout for tests to match msvc offsets (related to #355?)
Do not merge: this PR depends on #377 and should be rebased before
Also there's a lot of testing code and dirty places, which requires some tidying.

Implement offsetof as builtin

---

Cesium.CodeGen/Contexts/AssemblyContext.cs

With that function we have two references to System.Runtime when targeting .NET

Remove not needed function which left after rebase

---

Cesium.CodeGen.Tests/CodeGenOperatorTests.cs
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.CompoundAssignment.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.CompoundAssignmentAsValue.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.IncrementAsValue.verified.txt
Cesium.CodeGen/Ir/BlockItems/ExpressionStatement.cs
Cesium.CodeGen/Ir/Expressions/SetValueExpression.cs
Cesium.IntegrationTests/switch/duff_device.c
Cesium.IntegrationTests/switch/no_side_effects.c
Cesium.IntegrationTests/value_assignments.c

SetValueExpression has invalid type - type is always equal to type of value to set, but actual emitted code always leave empty stack, so SetValueExpression cannot be used as value and when it is used compiler produces invalid IL.
This PR fixes that - compound assignments now work correctly
This allows `while (i += 1)` and `while (i++)` to be compiled correctly
Fun fact - this code will result in 1 in `i`
```
var i = 0;
i += i += 1;
```
(there's no sequence points, so who cares, but this it worth noting)
- Closes #409.
- Closes #411.

Fix SetValueExpression emitting

---

Cesium.CodeGen/Ir/BlockItems/CompoundStatement.cs
Cesium.CodeGen/Ir/BlockItems/DeclarationBlockItem.cs
Cesium.CodeGen/Ir/BlockItems/InitializationBlockItem.cs
Cesium.CodeGen/Ir/BlockItems/SwitchStatement.cs
Cesium.CodeGen/Ir/Expressions/ConsumeExpression.cs
Cesium.CodeGen/Ir/Expressions/LocalArrayAllocationExpression.cs

WIP: this PR is based on #403, which is not merged now
Look at the last commit
This PR removes LowerInitializers specialization from CompoundStatement and DeclarationBlockItem, latter is now lowered to the new InitializationBlockItem thing, which just emits initializers in a sequence.
New expression - LocalArrayAllocationExpression - is added to replace hacks and specialized emit in DeclarationBlockItem.
LocalArrayAllocationExpression is currently delegates to InPlaceArrayType.EmitInitializer  (this can be changed by just moving that code from I.P.A.T to that expression)
Few hacks less from the CodeGen

Remove LowerInitializers

---

Cesium.CodeGen.Tests/CodeGenOperatorTests.cs
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.VoidCommaOperator.verified.txt
Cesium.CodeGen/Ir/Expressions/CommaExpression.cs
Cesium.IntegrationTests/comma_operator.c

This PR fixes CommaExpression emit when left expression returns void - there's nothing to pop from the stack in this case

Foolproof comma operator

---

Cesium.Parser/CParser.cs
Cesium.Preprocessor/CPreprocessor.cs
README.md

- Remove no longer needed TODO comments.
- Update the completion percentage in the `README` file.
- Fix the `#pragma` processing to skip unknown pragmas.

Small preprocessor update

---

Cesium.IntegrationTests/Cesium.IntegrationTests.csproj
Cesium.IntegrationTests/IntegrationTestContext.cs
Cesium.IntegrationTests/IntegrationTestRunner.cs
Cesium.IntegrationTests/WindowsEnvUtil.cs
Cesium.Test.Framework/Cesium.Test.Framework.csproj
Cesium.Test.Framework/DotNetCliHelper.cs
Cesium.Test.Framework/ExecUtil.cs
Cesium.sln.DotSettings

For more stable testing, we have to pass `MSBUILDENSURESTDOUTFORTASKPROCESSES = 0` to any dotnet build processes.
See https://github.com/dotnet/sdk/issues/34653 for details.

Tests: add a workaround for https://github.com/dotnet/sdk/issues/34653

---

Cesium.CodeGen/ICompilerReporter.cs
Cesium.Compiler.Tests/Cesium.Compiler.Tests.csproj
Cesium.Compiler.Tests/CommandLineParsingTest.cs
Cesium.Compiler.Tests/MockCompilerReporter.cs
Cesium.Compiler.Tests/Usings.cs
Cesium.Compiler/Cesium.Compiler.csproj
Cesium.Compiler/CommandLineParser.cs
Cesium.Compiler/Main.cs
Cesium.sln

It's hard to make GCC/clang compatible CLI switches with command line parser, this PR make parsing self-contained and I expect that we rewrite it to handwritten parser eventually.

Abstract command line parser

---

Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.Compiler/stdlib/stdio.h
Cesium.Compiler/stdlib/stdlib.h
Cesium.Runtime/StdIoFunctions.cs
Cesium.Runtime/StdLibFunctions.cs

Also have to lower expression passed to varargs before performing implicit cast

Add atoi/fprintf

---

Cesium.Compiler/Compilation.cs
Cesium.Parser.Tests/PreprocessorTests/PreprocessorTests.cs
Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.FunctionReplaceEllipsis.verified.txt
Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.FunctionReplaceEllipsisMultipleParameters.verified.txt
Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.FunctionReplaceEllipsisMultipleParameters2.verified.txt
Cesium.Parser.Tests/PreprocessorTests/verified/PreprocessorTests.FunctionWithoutParameters.verified.txt
Cesium.Preprocessor/CPreprocessor.cs
Cesium.Preprocessor/CPreprocessorMacroDefinitionParser.cs
Cesium.Preprocessor/IMacroContext.cs
Cesium.Preprocessor/InMemoryDefinesContext.cs
Cesium.Preprocessor/MacroDefinitions.cs

There were a few bugs with the function-like macro, I have tested many cases and this commit seems to fix several things and add support for ... and __VA_ARGS__
Let me know if there is something I am missing here

#429 Preprocessor: ... and __VA_ARGS__ support

---

Cesium.Ast/Expressions.cs
Cesium.CodeGen/Extensions/ExpressionEx.cs
Cesium.CodeGen/Ir/Expressions/StringLiteralListExpression.cs
Cesium.IntegrationTests/strings/string_literals.c
Cesium.Parser/CParser.cs

Closes #446. It is a simple solution that works for now. However, it doesn't support the _encoding-prefix_ yet, but this is a good start.
Please let me know if I am missing something here.
> Semantics
5. In translation phase 6, the multibyte character sequences specified by any sequence of adjacent character and identically-prefixed string literal tokens are concatenated into a single multibyte character sequence.

 String literal concatenation

---

Cesium.CodeGen.Tests/CodeGenArrayTests.cs
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayInitializationWithoutSize.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayParameterPassing.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.GlobalArrayInitializationWithoutSize.verified.txt
Cesium.CodeGen/Ir/Declarations/LocalDeclarationInfo.cs
Cesium.CodeGen/Ir/Declarations/ScopedDeclarationInfo.cs
Cesium.IntegrationTests/array/array_initialization.c

I think this should fix #422, I am not sure if I took the right approach, but it is working.
I wanted to add an integration test to make this work, but it seems that sizeof(array) is not working, any ideas on how to test this feature?
One of my changes is close to TODO #126, but I didn't know what to do with it, since it is working in both scenarios mentioned in that issue.

#422 Added support for array initialization without size

---

Cesium.CodeGen/Extensions/TranslationUnitEx.cs
Cesium.CodeGen/Extensions/TypeSystemEx.cs
Cesium.CodeGen/Ir/Expressions/CompoundInitializationExpression.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.CodeGen/Ir/Expressions/Values/LValueArrayElement.cs
Cesium.CodeGen/Ir/Lowering/BlockItemLowering.cs
Cesium.CodeGen/Ir/Types/IType.cs
Cesium.CodeGen/Ir/Types/InPlaceArrayType.cs

With the added benefit that some `int?` variables now became `int`

Used null-coalescing operator for nullable assignments

---

Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.StructParameters.verified.txt
Cesium.CodeGen/Contexts/BlockScope.cs
Cesium.CodeGen/Contexts/FunctionScope.cs
Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
Cesium.CodeGen/Contexts/IEmitScope.cs
Cesium.CodeGen/Contexts/Meta/FunctionInfo.cs
Cesium.CodeGen/Contexts/TranslationUnitContext.cs
Cesium.CodeGen/Extensions/TypeDefinitionEx.cs
Cesium.CodeGen/Ir/BlockItems/FunctionDefinition.cs
Cesium.CodeGen/Ir/Expressions/Values/LValueParameter.cs
Cesium.CodeGen/Ir/ParametersInfo.cs
Cesium.CodeGen/Ir/Types/FunctionType.cs

If forward declaration has different parameter name then code gen does not working

Fix codegen with forward declaration.

---

Cesium.Compiler/Cesium.Compiler.csproj

Apparently there's a problem with this s on Mac, so for now let's just disable.
Closes #496.

(#496) Do not try build AOT for macOS

---

Cesium.Parser/CParser.cs
README.md

Closes #441.
All the issues have been updated to C23 (with adding and removing the new items where appropriate). Cesium will target C23 from now on.

(#441) Docs: update references to the C23 standard

---

Cesium.CodeGen.Tests/CodeGenSwitchTests.cs
Cesium.CodeGen.Tests/verified/CodeGenSwitchTests.FallthroughCase.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenSwitchTests.NestedCases.verified.txt
Cesium.CodeGen/Ir/Lowering/BlockItemLowering.cs

Closes #408 
Codegen diff for `CodeGenSwitchTests.NestedCases`:
https://www.diffchecker.com/MLuXLwzS/ (left is main, right is PR)

(#408) Dedup labels for nested case statements

---

Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ConstArgcMain.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ConstConstMain.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.PointerPointerMain.verified.txt
Cesium.CodeGen/Ir/BlockItems/FunctionDefinition.cs

Now main functions using const int argc or const char * cosnt * argv or char * cont * argv are valid.
Issue #66

Improve Main function signature equivalency

---

Cesium.CodeGen.Tests/CodeGenNetInteropTests.cs
Cesium.CodeGen.Tests/verified/CodeGenNetInteropTests.TestEquivalentTypeAttribute_architecture=Dynamic.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenNetInteropTests.TestEquivalentTypeAttribute_architecture=Wide.verified.txt
Cesium.CodeGen/Extensions/TypeSystemEx.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
Cesium.CodeGen/Ir/Expressions/FunctionCallExpressionBase.cs
Cesium.Runtime.Tests/PtrTests.cs
Cesium.Runtime.Tests/StringTests.cs
Cesium.Runtime/Attributes/EquivalentTypeAttribute.cs
Cesium.Runtime/FuncPtr.cs
Cesium.Runtime/StringFunctions.cs
Cesium.Runtime/UTF8String.cs
Cesium.Runtime/VoidPtr.cs

A FuncPtr can now be turned into a corresponding Delegate and also a Delegate can be turned into a FuncPtr.
You can also use UTF8String instead of byte*. This is more convenient and it contains the fastest implementations of some methods for the corresponding .Net versions.

Improved cli-interop

---

build/Build.Sdk.cs

Not sure about the root cause, but this may probably fix some weird issues when running compiler targets subsequently

[sdk]: Possible fix missing/outdated artifacts before compiler packing

---

Cesium.IntegrationTests/stdlib/printf.c
Cesium.Runtime.Tests/StdIoFunctionTests.cs
Cesium.Runtime/StdIoFunctions.cs

1. I've updated our handling for `%lu` and `%li` to process argument as `long`, according to the standard.
2. Tests on Mac have started failing recently: it looks like Apple's GCC changed its mind on `long`'s size (?!): before, it was treating `%lu` as a prefix for a `uint32_t`, and now it's `uint64_t`.
(WTF, seriously.)
As a result, the test is currently not portable, so I'll comment it out and file an issue to fix it in a portable way.
Just another that Cesium programs for now use the same behavior on all the systems and expose `long` as `int64_t`.

fprintf: correctly process long prefix

---

Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfElseTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenIfTests.IfElseWithNestedDeclarationTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ImplicitReturnAllowedNonMain.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ReturnInsideInfiniteForTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ReturnValueInsideInfiniteForTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.VariablesInsideNestedIf.verified.txt
Cesium.CodeGen/Ir/BlockItems/FunctionDefinition.cs
Cesium.CodeGen/Ir/ControlFlow/ControlFlowChecker.cs
Cesium.IntegrationTests/functions.c
Cesium.IntegrationTests/if.c

- Allow missing return for non void functions.
- Make sure that unreachable code at the end of file has ret instruction.
Closes #633

Improve code generation for functions

---

Cesium.CodeGen.Tests/verified/CodeGenIncrementDecrementStatementTests.PostfixIncrementVariable.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenOperatorTests.IncrementAsValue.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenPointersTests.IncrementPrimitivePointer.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenPointersTests.IncrementStructPointer.verified.txt
Cesium.CodeGen/Ir/Expressions/PostfixIncrementDecrementExpression.cs
Cesium.IntegrationTests/value_assignments.c

- Add integration test for validation
Right now I use inefficient codegen, to make it more efficient we need introduce new node, and lowering.
Closes #646

Fix postifix operator

---

Cesium.CodeGen.Tests/verified/CodeGenTypeTests.MegaUnionDefinition.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.MultipleFieldStructWithUnionDefinition.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.SingleFieldStructWithUnionDefinition.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructWithUnionsAndAnons.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.SuperHardStructInitialization.verified.txt
Cesium.CodeGen/Contexts/AssemblyContext.cs
Cesium.CodeGen/Contexts/TranslationUnitContext.cs
Cesium.CodeGen/Ir/Expressions/Values/LValueInstanceField.cs
Cesium.CodeGen/Ir/Types/StructType.cs
Cesium.IntegrationTests/structs/structs_forward_declarations.c

when type was forward declared before child type which used inside that declared type later on, codegen was broken. This lead to simplification of the struct emit, since no need to special case anon types. This lead to changes in naming which I think is reasonable, since that way always anon types prefixed with <typedef>

Fix bug with codegeneration with forward declaration

---

Cesium.CodeGen/Ir/Expressions/Constants/CharConstant.cs

Also ignore \ before unknown escape char.

Add missing escape symbols

---

Cesium.CodeGen.Tests/CodeGenArrayTests.cs
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.ArrayStringComparison.verified.txt
Cesium.CodeGen/Ir/BlockItems/InitializationBlockItem.cs
Cesium.CodeGen/Ir/ControlFlow/ControlFlowChecker.cs
Cesium.CodeGen/Ir/Emitting/BlockItemEmitting.cs
Cesium.CodeGen/Ir/Expressions/CompoundInitializationExpression.cs
Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
Cesium.CodeGen/Ir/Lowering/BlockItemLowering.cs

This was require removal of special block item Initialization, and replace it with regular CompoundBlockExpression. That allow us unroll initialization expression into set of assignment. Without that we cannot introduce struct initialization later on.

Add support for array of strings initialization.

---

Cesium.CodeGen.Tests/CodeGenBinaryExpressionTests.cs
Cesium.CodeGen.Tests/verified/CodeGenBinaryExpressionTests.ArrayIndexerInBrackets.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenBinaryExpressionTests.ArrayIndexerInBracketsAfterMultiply.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenBinaryExpressionTests.ConversionForConst.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenBinaryExpressionTests.IdentifierInBrackets.verified.txt
Cesium.CodeGen/Ir/Expressions/BinaryOperators/BinaryOperatorExpression.cs
Cesium.CodeGen/Ir/Expressions/IndirectionExpression.cs
Cesium.CodeGen/Ir/Expressions/SubscriptingExpression.cs
Cesium.CodeGen/Ir/Expressions/TypeCastExpression.cs

Currently compiler do not know, if `(x)` is typecase or some identifier in the brackets, so we probe registered types. Also ignore constant specifiers when trying to find constant property on the type.

Distinguish identifiers and indirection which detected as typecasts

---

Cesium.Ast/Declarations.cs
Cesium.Parser.Tests/ParserTests/FullParserTests.cs
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.InlineFunction.verified.txt
Cesium.Parser.Tests/ParserTests/verified/FullParserTests.NoReturnFunction.verified.txt
Cesium.Parser/CParser.cs

They are harless in a sense that we can not even implement them. Inline can be taken care by JIT, and _Noreturn would be handled later, since it requrie control flow analysys which we are barely have and don't have expertise at all.
Related #211
Closes #706

Add parsing of function specifiers

---

Cesium.CodeGen.Tests/CodeGenTypeTests.cs
Cesium.CodeGen.Tests/verified/CodeGenTypeTests.StructForwardDeclaration.verified.txt
Cesium.CodeGen/Contexts/TranslationUnitContext.cs

Previously we support only forward declarations via typedef

Allow forward declaration of structs

---

Cesium.CodeGen.Tests/CodeGenMethodTests.cs
Cesium.CodeGen.Tests/verified/CodeGenMethodTests.InlineFunction.verified.txt
Cesium.CodeGen/Ir/BlockItems/FunctionDefinition.cs
Cesium.CodeGen/Ir/Lowering/BlockItemLowering.cs

Since codegen of inline functions was not working in #705, then instead of just removing specifiers, I put them into IR, and let somebody utilize it if needed.

Support inline and noreturn in IR

---

Cesium.Runtime.Tests/StdIoFunctionTests.cs
Cesium.Runtime/StdIoFunctions.cs

Closes #681
GCHandles on StreamHandles are allocated on the unmanaged heap (`AllocHGlobal`). A pointer to the GCHandle is used to control the StreamHandler. Locks are also added for thread-safe interaction.
Keeps all standard streams (stdin, stdout, stderr) in list `Handles`

StreamHandle interop

---

Cesium.CodeGen.Tests/CodeGenArrayTests.cs
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.StaticStringArrayTest.verified.txt
Cesium.CodeGen.Tests/verified/CodeGenArrayTests.StringArrayTest.verified.txt
Cesium.CodeGen/Extensions/TranslationUnitEx.cs
Cesium.CodeGen/Ir/Emitting/BlockItemEmitting.cs
Cesium.CodeGen/Ir/Lowering/BlockItemLowering.cs
Cesium.IntegrationTests/array/array_initialization.c

Now GlobalVariableDefinition used only during emitting phase, to indicate that we should define global field. Fixes #720

Unify handling global and local declarations

---

Cesium.Sdk.Tests/SdkTestBase.cs

This only fix Sdk tests and not Integration tests which a behave funny.
I prefer to go with #729 at least initially, and if there appetite for pursuing this, continue working on this PR.

Supply global.json

---

Cesium.Templates.CSharp/Cesium.Templates.CSharp.csproj
LICENSES/CC0-1.0.txt
README.md
REUSE.toml

Closes #682.
@seclerp, I'd ask you to please confirm in a comment that you are ok with this change.
It changes the license for some code you contributed (in the `Cesium.Templates.CSharp` directory exclusively, so — not much of your code. But still, a legally sensible portion of it.) from MIT to CC0, essentially meaning "(almost) no rights reserved".
This is done for the convenience of the templates' users. More motivation is stated in #682.

Legal: migrate the project templates under CC0 license
